feat: cshl genome informatics 2023 (#2644)
anvilproject/anvil-portal pull request #2650
Opened 2023-04-27 09:30 UTC by esthermcdade

Closes #2644

2023-04-27 22:47 UTC, frano-m commented on content/events/cshl-genome-informatics-2023.md
> +description: "TThe AnVIL team will attend the CSHL Genome Informatics meeting to share about the AnVIL platform with the genomics community. This meeting will draw together researchers focused on gen
```suggestion
description: "The AnVIL team will attend the CSHL Genome Informatics meeting to share about the AnVIL platform with the genomics community. This meeting will draw together researchers focused on genomic data science research, for which AnVIL can be a useful platform to leverage and can offer solutions to some common challenges in the field."
```

2023-04-27 22:48 UTC, frano-m commented on content/events/cshl-genome-informatics-2023.md
> +Tentative Meeting Topics:
@esthermcdade Insert a new line between lines 22 and 23 and view the change on localhost to see the difference.

2023-04-27 22:52 UTC, frano-m requested changes
@esthermcdade nice work - there is only one tiny change to be made. Thank you.

2023-04-28 03:50 UTC, NoopDog commented
@esthermcdade you will need to rebase this branch.

2023-04-28 06:20 UTC, frano-m approved these changes
Thank you @esthermcdade ⭐

2023-04-28 06:38 UTC, merged